// Bank accounts data
export const BANK_ACCOUNTS = [
  {
    key: "opay",
    label: "Opay",
    image: require("../../assets/images/opay.jpeg"),
    accountNumber: "8023562567",
    balance: 12000.5,
    history: [
      {
        id: 1,
        type: "outgoing",
        title: "Transfer to Inioluwa Abiodun",
        amount: 4000,
        date: "Jul 15",
        // from: "Opay",
        to: "GTB",
        accountNumber: "8023562567",
        status: "success",
        description: "Happy Birthday",
        time: "15:30",
        transactionId: "#1023231",
        reference: "#1023231",
        sessionId: "#1023231",
      },
      {
        id: 2,
        type: "incoming",
        title: "Transfer from John Doe",
        amount: 2500,
        date: "Jul 14",
        // from: "GTB",
        to: "Opay",
        accountNumber: "8023562567",
        status: "success",
        description: "Payment for services",
        time: "10:15",
        transactionId: "#1023232",
        reference: "#1023232",
        sessionId: "#1023232",
      },
    ],
  },
  {
    key: "kuda",
    label: "Kuda",
    image: require("../../assets/images/kuda.png"),
    accountNumber: "9550152944",
    balance: 5000,
    history: [
      {
        id: 3,
        type: "outgoing",
        title: "Transfer to Sarah Wilson",
        amount: 1500,
        date: "Jul 13",
        // from: "Kuda",
        to: "Zenith",
        accountNumber: "9550152944",
        status: "success",
        description: "Rent payment",
        time: "09:45",
        transactionId: "#1023233",
        reference: "#1023233",
        sessionId: "#1023233",
      },
      {
        id: 4,
        type: "incoming",
        title: "Salary payment",
        amount: 8000,
        date: "Jul 12",
        // from: "Company Ltd",
        to: "Kuda",
        accountNumber: "9550152944",
        status: "success",
        description: "Monthly salary",
        time: "08:00",
        transactionId: "#1023234",
        reference: "#1023234",
        sessionId: "#1023234",
      },
    ],
  },
  {
    key: "paystack",
    label: "Paystack Titan",
    image: require("../../assets/images/paystack.png"),
    accountNumber: "7528129422",
    balance: 200.5,
    history: [
      {
        id: 5,
        type: "outgoing",
        title: "Online purchase",
        amount: 150,
        date: "Jul 11",
        from: "Paystack Titan",
        // to: "Amazon",
        accountNumber: "7528129422",
        status: "success",
        description: "Book purchase",
        time: "14:20",
        transactionId: "#1023235",
        reference: "#1023235",
        sessionId: "#1023235",
      },
    ],
  },
  {
    key: "moniepoint",
    label: "Moniepoint",
    image: require("../../assets/images/moniepoint.jpg"),
    accountNumber: "4321356765",
    balance: 8000.75,
    history: [
      {
        id: 6,
        type: "outgoing",
        title: "Transfer to Mom",
        amount: 3000,
        date: "Jul 10",
        // from: "Moniepoint",
        to: "Access Bank",
        accountNumber: "4321356765",
        status: "success",
        description: "Monthly allowance",
        time: "16:30",
        transactionId: "#1023236",
        reference: "#1023236",
        sessionId: "#1023236",
      },
      {
        id: 7,
        type: "incoming",
        title: "Freelance payment",
        amount: 5000,
        date: "Jul 9",
        from: "Client XYZ",
        to: "Moniepoint",
        accountNumber: "4321356765",
        status: "success",
        description: "Project completion",
        time: "11:00",
        transactionId: "#1023237",
        reference: "#1023237",
        sessionId: "#1023237",
      },
    ],
  },
];

// Transaction history data
export const TRANSACTION_HISTORY = [
  {
    id: 1,
    type: "outgoing",
    title: "Transfer to Inioluwa Abiodun",
    amount: 4000,
    date: "Jul 15",
    from: "Opay",
    to: "GTB",
    accountNumber: "8023562567",
    status: "success",
    description: "Happy Birthday",
    time: "15:30",
    transactionId: "#1023231",
    reference: "#1023231",
    sessionId: "#1023231",
  },
  {
    id: 2,
    type: "incoming",
    title: "Transfer from Moshood Jimoh-Kuku",
    amount: 2000,
    date: "Jul 15",
    from: "Opay",
    to: "Kuda",
    accountNumber: "9024565245",
    status: "success",
    description: "Happy Birthday",
    time: "15:30",
    transactionId: "#1023232",
    reference: "#1023232",
    sessionId: "#1023232",
  },
  {
    id: 3,
    type: "outgoing",
    title: "Transfer to David Omokanye",
    amount: 2400,
    date: "Jul 15",
    from: "Opay",
    to: "Kuda",
    accountNumber: "0723653827",
    status: "success",
    description: "Happy Birthday",
    time: "15:30",
    transactionId: "#1023233",
    reference: "#1023233",
    sessionId: "#1023233",
  },
];
